### ISSUE TITLE
Build problems with Auth::Integrated

### ISSUE THREAD

**Issue by Pyzyryab** [prisma/tiberius#283]
I am writting an ORM that depends on `tiberius`. Someone requested us to include the `Integrated` auth method for MSSQL databases, so we go ahead, and tried. 

Everything works well in our local dev machines, but in our actions, for both Unix and Windows targets we are unable to build our library.

This is the specific error for Unix systems:
```
error: failed to run custom build command for `libgssapi-sys v0.2.4`

Caused by:
  process didn't exit successfully: `/home/runner/work/Canyon-SQL/Canyon-SQL/target/debug/build/libgssapi-sys-9275876cf6817fbf/build-script-build` (exit status: 101)
  --- stdout
  cargo:rustc-link-lib=gssapi_krb5

  --- stderr
  [/home/runner/.cargo/registry/src/github.com-1ecc6299db9ec823/libgssapi-sys-0.2.4/build.rs:9] res = Ok(
      Output {
          status: ExitStatus(
              unix_wait_status(
                  0,
              ),
          ),
          stdout: "",
          stderr: "",
      },
  )
  [/home/runner/.cargo/registry/src/github.com-1ecc6299db9ec823/libgssapi-sys-0.2.4/build.rs:9] res = Ok(
      Output {
          status: ExitStatus(
              unix_wait_status(
                  0,
              ),
          ),
          stdout: "",
          stderr: "",
      },
  )
  [/home/runner/.cargo/registry/src/github.com-1ecc6299db9ec823/libgssapi-sys-0.2.4/build.rs:9] res = Ok(
      Output {
          status: ExitStatus(
              unix_wait_status(
                  0,
              ),
          ),
          stdout: "",
          stderr: "",
      },
  )
  [/home/runner/.cargo/registry/src/github.com-1ecc6299db9ec823/libgssapi-sys-0.2.4/build.rs:9] res = Ok(
      Output {
          status: ExitStatus(
              unix_wait_status(
                  0,
              ),
          ),
          stdout: "",
          stderr: "",
      },
  )
  [/home/runner/.cargo/registry/src/github.com-1ecc6299db9ec823/libgssapi-sys-0.2.4/build.rs:9] res = Ok(
      Output {
          status: ExitStatus(
              unix_wait_status(
                  0,
              ),
          ),
          stdout: "",
          stderr: "",
      },
  )
  [/home/runner/.cargo/registry/src/github.com-1ecc6299db9ec823/libgssapi-sys-0.2.4/build.rs:9] res = Ok(
      Output {
          status: ExitStatus(
              unix_wait_status(
                  0,
              ),
          ),
          stdout: "",
          stderr: "",
      },
  )
  [/home/runner/.cargo/registry/src/github.com-1ecc6299db9ec823/libgssapi-sys-0.2.4/build.rs:9] res = Ok(
      Output {
          status: ExitStatus(
              unix_wait_status(
                  0,
              ),
          ),
          stdout: "",
          stderr: "",
      },
  )
  [/home/runner/.cargo/registry/src/github.com-1ecc6299db9ec823/libgssapi-sys-0.2.4/build.rs:9] res = Ok(
      Output {
          status: ExitStatus(
              unix_wait_status(
                  0,
              ),
          ),
          stdout: "",
          stderr: "",
      },
  )
  [/home/runner/.cargo/registry/src/github.com-1ecc6299db9ec823/libgssapi-sys-0.2.4/build.rs:9] res = Ok(
      Output {
          status: ExitStatus(
              unix_wait_status(
                  0,
              ),
          ),
          stdout: "",
          stderr: "",
      },
  )
  [/home/runner/.cargo/registry/src/github.com-1ecc6299db9ec823/libgssapi-sys-0.2.4/build.rs:9] res = Ok(
      Output {
          status: ExitStatus(
              unix_wait_status(
                  0,
              ),
          ),
          stdout: "",
          stderr: "",
      },
  )
  [/home/runner/.cargo/registry/src/github.com-1ecc6299db9ec823/libgssapi-sys-0.2.4/build.rs:9] res = Ok(
      Output {
          status: ExitStatus(
              unix_wait_status(
                  0,
              ),
          ),
          stdout: "",
          stderr: "",
      },
  )
  [/home/runner/.cargo/registry/src/github.com-1ecc6299db9ec823/libgssapi-sys-0.2.4/build.rs:9] res = Ok(
      Output {
          status: ExitStatus(
              unix_wait_status(
                  0,
              ),
          ),
          stdout: "",
          stderr: "",
      },
  )
  [/home/runner/.cargo/registry/src/github.com-1ecc6299db9ec823/libgssapi-sys-0.2.4/build.rs:9] res = Ok(
      Output {
          status: ExitStatus(
              unix_wait_status(
                  0,
              ),
          ),
          stdout: "/usr/lib/x86_64-linux-gnu/libgssapi_krb5.so.2\n/usr/lib/x86_64-linux-gnu/libgssapi_krb5.so.2.2\n",
          stderr: "",
      },
  )
  src/wrapper_mit.h:1:10: fatal error: 'gssapi.h' file not found
  src/wrapper_mit.h:1:10: fatal error: 'gssapi.h' file not found, err: true
Error:   thread 'main' panicked at 'failed to generate gssapi bindings: ()', /home/runner/.cargo/registry/src/github.com-1ecc6299db9ec823/libgssapi-sys-0.2.4/build.rs:80:10
  note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
warning: build failed, waiting for other jobs to finish...
Error: Process completed with exit code 101.
```
You can read it here: https://github.com/zerodaycode/Canyon-SQL/actions/runs/4666217730/jobs/8260547851

And for Windows:
```
https://github.com/zerodaycode/Canyon-SQL/actions/runs/4666217730/jobs/8260548158
```
I am not pasting the full log because it does not specifically points towards the same kind of error with `gssapi`,  but only happens in our newer builds, after asking a tiberius to use the `integrated-auth-gssapi` feature.

This is our actual dependency: `tiberius = { version = "0.12.1", features = ["tds73", "chrono", "integrated-auth-gssapi"] }`

Are you guys already faced this kind of errors?

Thanks before hand for your time

**Comment by willbush** [comment]
See my comment [here](https://github.com/prisma/tiberius/issues/293#issuecomment-1585196262). I think you're having the same issue as #293.

**Comment by wyhaya** [comment]
I'm getting a similar error on macOS, on `12.6` it works fine, but on `13.5` it won't compile.

```bash
cargo run --example tokio --features integrated-auth-gssapi
```

Error:
```
Caused by:
  process didn't exit successfully: `/Users/.../tiberius/target/debug/build/libgssapi-sys-699af3597fa43222/build-script-build` (exit status: 101)
  --- stdout
  cargo:rustc-link-lib=framework=GSS

  --- stderr
  src/wrapper_apple.h:1:10: fatal error: 'GSS/GSS.h' file not found
  src/wrapper_apple.h:1:10: note: did not find header 'GSS.h' in framework 'GSS' (loaded from '/System/Library/Frameworks')
  src/wrapper_apple.h:1:10: fatal error: 'GSS/GSS.h' file not found, err: true
  thread 'main' panicked at 'failed to generate gssapi bindings: ()', /Users/../.cargo/registry/src/index.crates.io-6f17d22bba15001f/libgssapi-sys-0.2.4/build.rs:80:10
  note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
```

**Comment by MattJackson** [comment]
If you specifically need `Auth::Integrated`, it still builds against libgssapi-sys, so this build issue looks unaddressed on that path. As an alternative, the sspi-rs feature in #442 provides a Windows/NTLM auth path on Unix that doesn't depend on libgssapi. Leaving open to track the Integrated build path.
